#!/usr/bin/env python3
#
# (c) Stephen Bates 2022
#

import argparse
import json
import os
import sys

if __name__=="__main__":

    desc = "Parse the Emporia Vue energy monitoring cloud for a user's devices."

    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument("username",
                        help="the username for the Emporia Vue account.")
    parser.add_argument("password",
                        help="the password for the Emporia Vue account.")
    args = parser.parse_args()

    try:
        import pyemvue
        import prometheus_client
    except ModuleNotFoundError:
        sys.exit("Required modules not found. Please install them via pip!")

class EmVueExporter(object):

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __enter__(self):
        self.vue = pyemvue.PyEmVue()
        if os.path.exists('./keys.json'):
            with open('keys.json') as f:
                data = json.load(f)
            self.vue.login(id_token=data['id_token'],
                           access_token=data['access_token'],
                           refresh_token=data['refresh_token'],
                           token_storage_file='keys.json')
        else:
            self.vue.login(username=self.username,
                           password=self.password,
                           token_storage_file='keys.json')

        return self

    def __exit__(self, exc_type, exc_value, exc_traceback):
        pass

if __name__ == "__main__":

    with EmVueExporter(args.username, args.password) as v:
        print(v)
